parameters:
#    accounting_sale_offers.example.class: Accounting\SaleOffersBundle\Example

services:
#    accounting_sale_offers.example:
#        class: %accounting_sale_offers.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
