parameters:
#    accounting_supplier_prestations.example.class: Accounting\SupplierPrestationsBundle\Example

services:
#    accounting_supplier_prestations.example:
#        class: %accounting_supplier_prestations.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
