accounting_charges:
    resource: "@AccountingChargesBundle/Resources/config/routing.yml"
    prefix:   /

accounting_supplier_prestations:
    resource: "@AccountingSuppliersProductsBundle/Resources/config/routing.yml"
    prefix:   /

accounting_offers:
    resource: "@AccountingOffersBundle/Resources/config/routing.yml"
    prefix:   /

accounting_profit:
    resource: "@AccountingProfitBundle/Resources/config/routing.yml"
    prefix:   /

accounting_sale_offers:
    resource: "@AccountingSaleOffersBundle/Resources/config/routing.yml"
    prefix:   /

accounting_sale_prestations:
    resource: "@AccountingSaleProductsBundle/Resources/config/routing.yml"
    prefix:   /

accounting_warehouse:
    resource: "@AccountingWarehouseBundle/Resources/config/routing.yml"
    prefix:   /

accounting_deliveries:
    resource: "@AccountingDeliveriesBundle/Resources/config/routing.yml"
    prefix:   /

accounting_main:
    resource: "@AccountingMainBundle/Resources/config/routing.yml"
    prefix:   /

accounting_price_list:
    resource: "@AccountingPriceListBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
