parameters:
#    accounting_deliveries.example.class: Accounting\DeliveriesBundle\Example

services:
#    accounting_deliveries.example:
#        class: %accounting_deliveries.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
