parameters:
#    common_data.example.class: Common\DataBundle\Example

services:
#    common_data.example:
#        class: %common_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
