parameters:
#    accounting_price_list.example.class: Accounting\PriceListBundle\Example

services:
#    accounting_price_list.example:
#        class: %accounting_price_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
