parameters:
#    accounting_main.example.class: Accounting\MainBundle\Example

services:
#    accounting_main.example:
#        class: %accounting_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
