parameters:
#    accounting_charges.example.class: Accounting\ChargesBundle\Example

services:
#    accounting_charges.example:
#        class: %accounting_charges.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
