parameters:
#    accounting_offers.example.class: Accounting\OffersBundle\Example

services:
#    accounting_offers.example:
#        class: %accounting_offers.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
