parameters:
#    accounting_sale_prestations.example.class: Accounting\SaleProductsBundle\Example

services:
#    accounting_sale_prestations.example:
#        class: %accounting_sale_prestations.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
